# Generated by Django 3.2.7 on 2021-10-03 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models.verification_token


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_alter_user_first_name")]

    operations = [
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="Modified At")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Instance marked deleted"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Instance marked Active"),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.accounts.models.verification_token.activation_token,
                        help_text="token that is used for verification",
                        max_length=4,
                        verbose_name="Token",
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[("SMS", "sms"), ("EMAIL", "email")],
                        default="EMAIL",
                        help_text="How this token is going to be used select from the choices",
                        max_length=32,
                        verbose_name="Token Type",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Weather the token is valid or not (True means valid)",
                        verbose_name="Is Valid",
                    ),
                ),
                (
                    "number_attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Max number for a token be valid are 3",
                        verbose_name="Number Attempts",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Pass more information here in extra data",
                        verbose_name="Extra Data",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User for which the verification token to created",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Token",
                "verbose_name_plural": "Verification Tokens",
            },
        )
    ]
