# Generated by Django 3.2.7 on 2022-01-26 21:18

from django.db import migrations, models

import apps.accounts.models.blog


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_blog")]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.blog.upload_to,
                verbose_name="Image",
            ),
        )
    ]
