version: "3"


services:
  api:
    container_name: portfolio
    restart: always
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        app: portfolio
    ports:
      - "80:80"
    env_file: .env.prod
