version: "3"


services:
  api:
    container_name: portfolio
    restart: always
    build:
      context: .
      dockerfile: deployment/Dockerfile
    volumes:
      - .:/app
    ports:
      - "80:80"
