version: "3"

services:
  portfolio-backend-django:
    container_name: portfolio_backend_django
    restart: always
    build:
      context: .
      dockerfile: config/prod/Dockerfile
      args:
        PROJECT: portfolio_backend_django
        REQUIREMENTS: production.txt
    volumes:
      - .:/app
    ports:
      - "80:80"
    env_file: .env.prod
