version: "3"


services:
  api:
    container_name: portfolio
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        app: portfolio
        requirements: production.txt
    ports:
      - "80:80"
    env_file: .env
