# Generated by Django 3.2.7 on 2021-12-27 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_auto_20210927_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityconfig',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Extra Data'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Extra Data'),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Instance marked deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Instance marked Active')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Extra Data')),
                ('device_token', models.CharField(db_index=True, max_length=256, verbose_name='Device Token')),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android'), ('IPHONE', 'IPhone')], default='ANDROID', max_length=16, verbose_name='Device Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
            },
        ),
    ]
