# Generated by Django 3.2.7 on 2021-10-06 05:59

from django.db import migrations, models

import apps.contact.models.social_links


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="Modified At")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Instance marked deleted"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Instance marked Active"),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email"),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="Contact number"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={"verbose_name": "Contact Form", "verbose_name_plural": "Contact Forms"},
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="Modified At")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Instance marked deleted"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Instance marked Active"),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Type of notification")),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.contact.models.social_links.upload_to, verbose_name="Image"
                    ),
                ),
            ],
            options={"verbose_name": "Social link", "verbose_name_plural": "Social links"},
        ),
    ]
