# Generated by Django 3.2.7 on 2021-10-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Contact me form', 'verbose_name_plural': 'Contact me forms'},
        ),
        migrations.AddField(
            model_name='sociallink',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Name'),
        ),
    ]
