# Generated by Django 3.0.5 on 2021-08-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_first_n_ce4fe7_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'username', 'phone'], name='accounts_us_email_63302e_idx'),
        ),
    ]
