# Generated by Django 3.2.7 on 2021-09-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user             should be treated as active.             Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
