# Generated by Django 3.2.7 on 2021-10-05 08:39

from django.db import migrations, models
import portfolio.models.skills


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Instance marked deleted')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Instance marked Active')),
                ('name', models.CharField(max_length=64, verbose_name='Skill Name')),
                ('image', models.ImageField(upload_to=portfolio.models.skills.upload_to, verbose_name='Image')),
                ('level', models.CharField(blank=True, choices=[('ADVANCE', 'Advance'), ('INTERMEDIATE', 'Intermediate'), ('BEGINNER', 'Beginner')], max_length=32, null=True, verbose_name='Level')),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='extra data')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
